#!/bin/sh

touch cSpec.h

cat << EOF > cSpec.h
#ifndef __CSPEC_H_
#define __CSPEC_H_
EOF

for value in src/includes.h \
    src/helpers.h \
    src/data_structures.h \
    src/functionality.h \
    src/interface.h \
    src/assert_modules/charptr_array_assert.h \
    src/assert_modules/charptr_assert.h \
    src/assert_modules/double_array_assert.h \
    src/assert_modules/double_assert.h \
    src/assert_modules/expression_assert.h \
    src/assert_modules/int_array_assert.h \
    src/assert_modules/int_assert.h
do
    cat $value >> cSpec.h
done

cat << EOF >> cSpec.h

#endif
EOF

rm -rf export
mkdir export
mv cSpec.h export/
