#!/bin/sh

cat << EOF > cSpec.h
#ifndef __CSPEC_H_
#define __CSPEC_H_
EOF

for value in includes.h data_structures.h interface.h functionality.h asserts.h
do
    tail -n +7 $value | head -n -1 >> cSpec.h
done

cat << EOF >> cSpec.h

#endif
EOF

mv cSpec.h ../
cp assert_modules -r ../