#!/bin/sh

cd ..
make
cd examples

cd prime_factors
make clean
make
cd ..

cd simple
make clean
make
cd ..

cd stack
make clean
make
cd ..

cd string
make clean
make
cd ..

cd vector
make clean
make
cd ..

